name: mlaku_mlaku
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  bloc: ^8.1.2

  cloud_firestore: ^4.13.2

  dio: ^5.3.3
  equatable: ^2.0.5
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_carousel_widget: ^2.1.2
  flutter_native_splash: ^2.3.5
  get_it: ^7.6.4
  intl: ^0.18.1
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/promo/

flutter_native_splash:
  android: true
  ios: false
  web: false

  background_image: assets/image/splash.jpg
