// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9XBf8csMvnCwDp8u63Q3LErWGT0OTcHE',
    appId: '1:46631294289:web:4ff1cd66bd478f6d946f70',
    messagingSenderId: '46631294289',
    projectId: 'mlaku-malku',
    authDomain: 'mlaku-malku.firebaseapp.com',
    storageBucket: 'mlaku-malku.appspot.com',
    measurementId: 'G-QYB19N284Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKCJCAqw9qwd8Q3tb_3Fu2EEBLSP1GQzw',
    appId: '1:46631294289:android:582859162ec9e879946f70',
    messagingSenderId: '46631294289',
    projectId: 'mlaku-malku',
    storageBucket: 'mlaku-malku.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNcsPKeqzW2Gs-eYl_jqiR0vc9PaiLBQA',
    appId: '1:46631294289:ios:ff0a7ed9d98fb3c4946f70',
    messagingSenderId: '46631294289',
    projectId: 'mlaku-malku',
    storageBucket: 'mlaku-malku.appspot.com',
    iosBundleId: 'com.example.mlakuMlaku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNcsPKeqzW2Gs-eYl_jqiR0vc9PaiLBQA',
    appId: '1:46631294289:ios:38dff19b610a07ef946f70',
    messagingSenderId: '46631294289',
    projectId: 'mlaku-malku',
    storageBucket: 'mlaku-malku.appspot.com',
    iosBundleId: 'com.example.mlakuMlaku.RunnerTests',
  );
}
